image: Visual Studio 2015

environment:
  ZLIB_ROOT: C:\Program Files (x86)\zlib
  ZPG_ROOT: C:\Program Files (x86)\libZpg
  
cache:
  - C:\Program Files (x86)\zlib
  
install:
  - cd c:\projects
  # Download ZLib Source
  - IF NOT EXIST "%ZLIB_ROOT%" (
    md "%ZLIB_ROOT%" &&
    curl -LfsS -o zlib-1.2.11.tar.gz http://zlib.net/zlib-1.2.11.tar.gz &&
    7z x zlib-1.2.11.tar.gz &&
    7z x zlib-1.2.11.tar &&
    cd zlib-1.2.11 &&
    md build32 & cd build32 &&
    cmake -Werror=dev -G"Visual Studio 14 2015" .. &&
    cd .. &&
    cmake --build build32 --config Release --target install &&
    cd ..)
  - cd c:\projects\zpg

before_build:
- cmd: |
    md build32-release & cd build32-release
    cmake -Werror=dev -G "Visual Studio 14 2015" -DCMAKE_BUILD_TYPE=Release ..
    cd ..
    md build32-debug & cd build32-debug
    cmake -Werror=dev -G "Visual Studio 14 2015" -DCMAKE_BUILD_TYPE=Debug ..
    cd ..
    
build_script:
- cmd: |
    cmake --build build32-release --config Release --target Zpg
    cmake --build build32-release --config Release --target zpg_packer
    cmake --build build32-release --config Release --target install
    cmake --build build32-release --config Release --target package
    cmake --build build32-debug --config Debug --target Zpg
    cmake --build build32-debug --config Debug --target zpg_packer
    cmake --build build32-debug --config Debug --target install
    cmake --build build32-debug --config Debug --target package

test_script:
- cmd: |
    "%ZPG_ROOT%\bin\zpg_packer.exe" test.zpg -C -A tools/
    "%ZPG_ROOT%\bin\zpg_packer.exe" test.zpg -L
    "%ZPG_ROOT%\bin\zpg_packer.exe" test.zpg -E tools/test.jpg
    
artifacts:
  - path: build32/*.zip
    name: libZpg
