image: Visual Studio 2015

environment:
  matrix:
    - ZLIB_ROOT: C:\Program Files (x86)\zlib
      ZPG_ROOT: C:\Program Files (x86)\libZpg
      CMAKE_GENERATOR: Visual Studio 14 2015
      CMAKE_BUILD_TYPE: Debug
      ZPG_PACKER_NAME: zpg_packer_d
    - ZLIB_ROOT: C:\Program Files (x86)\zlib
      ZPG_ROOT: C:\Program Files (x86)\libZpg
      CMAKE_GENERATOR: Visual Studio 14 2015
      CMAKE_BUILD_TYPE: Release
      ZPG_PACKER_NAME: zpg_packer
    - ZLIB_ROOT: C:\Program Files\zlib
      ZPG_ROOT: C:\Program Files\libZpg
      CMAKE_GENERATOR: Visual Studio 14 2015 Win64
      CMAKE_BUILD_TYPE: Debug
      ZPG_PACKER_NAME: zpg_packer_d
    - ZLIB_ROOT: C:\Program Files\zlib
      ZPG_ROOT: C:\Program Files\libZpg
      CMAKE_GENERATOR: Visual Studio 14 2015 Win64
      CMAKE_BUILD_TYPE: Release
      ZPG_PACKER_NAME: zpg_packer

matrix:
  allow_failures:
    - platform: x86
      configuration: Debug
    - platform: x86
      configuration: Release
    - platform: x64
      configuration: Debug
    - platform: x64
      configuration: Release

cache:
  #- C:\Program Files (x86)\zlib
  
install:
  - echo Parametros %CMAKE_BUILD_TYPE% - %CMAKE_GENERATOR% -
  - cd c:\projects
  # Download ZLib Source
  - IF NOT EXIST "%ZLIB_ROOT%" (
    curl -LfsS -o zlib-1.2.11.tar.gz http://zlib.net/zlib-1.2.11.tar.gz &&
    7z x zlib-1.2.11.tar.gz &&
    7z x zlib-1.2.11.tar &&
    cd zlib-1.2.11 &&
    md build & cd build &&
    cmake -Werror=dev -G"%CMAKE_GENERATOR%" .. &&
    cd .. &&
    cmake --build build --config %CMAKE_BUILD_TYPE% --target install &&
    cd ..)
  - cd c:\projects\zpg

before_build:
- cmd: |
    md build & cd build
    cmake -Werror=dev -G "%CMAKE_GENERATOR%" -DCMAKE_BUILD_TYPE=%CMAKE_BUILD_TYPE% -DZLIB_ROOT=%ZLIB_ROOT% ..
    cd ..
    
build_script:
- cmd: |
    cmake --build build --config %CMAKE_BUILD_TYPE% --target Zpg
    cmake --build build --config %CMAKE_BUILD_TYPE% --target zpg_packer
    cmake --build build --config %CMAKE_BUILD_TYPE% --target install
    cmake --build build --config %CMAKE_BUILD_TYPE% --target package

test_script:
- cmd: |
    "%ZPG_ROOT%\bin\%ZPG_PACKER_NAME%.exe" test.zpg -C -A tools/
    "%ZPG_ROOT%\bin\%ZPG_PACKER_NAME%.exe" test.zpg -L
    "%ZPG_ROOT%\bin\%ZPG_PACKER_NAME%.exe" test.zpg -E tools/test.jpg
    
artifacts:
  - path: build/*.zip
    name: libZpg