image: Visual Studio 2015

environment:
  ZPG_ROOT: C:\Program Files (x86)\libZpg
  
cache:
  - C:\Program Files (x86)\zlib

before_build:
- cmd: |
    md build32\Release & cd build32
    cmake -Werror=dev -G "Visual Studio 14 2015" ..
    cd ..
    
build_script:
- cmd: |
    cmake --build build32 --config Release --target Zpg
    cmake --build build32 --config Release --target zpg_packer
    cmake --build build32 --config Release --target install

test_script:
- cmd: |
    "%ZPG_ROOT%\bin\zpg_packer.exe" test.zpg -C -A tools/
    "%ZPG_ROOT%\bin\zpg_packer.exe" test.zpg -L
    "%ZPG_ROOT%\bin\zpg_packer.exe" test.zpg -E tools/test.jpg
