image: Visual Studio 2015

environment:
  ZLIB_ROOT: C:\Program Files (x86)\zlib
  ZPG_ROOT: C:\Program Files (x86)\libZpg
  
cache:
  - C:\Program Files (x86)\zlib
  
install:
  - cd c:\projects
  # Download ZLib Source
  - IF NOT EXIST "%ZLIB_ROOT%" (
    md "%ZLIB_ROOT%" &&
    curl -LfsS -o zlib-1.2.11.tar.gz http://zlib.net/zlib-1.2.11.tar.gz &&
    7z x zlib-1.2.11.tar.gz &&
    7z x zlib-1.2.11.tar &&
    cd zlib-1.2.11 &&
    md build32 & cd build32 &&
    cmake -Werror=dev -G"Visual Studio 14 2015" .. &&
    cd .. &&
    cmake --build build32 --config Release --target install &&
    cd ..)
  - cd c:\projects\zpg

before_build:
- cmd: |
    md build32\Release & cd build32
    cmake -Werror=dev -G "Visual Studio 14 2015" ..
    cd ..
    
build_script:
- cmd: |
    cmake --build build32 --config Release --target Zpg
    cmake --build build32 --config Release --target zpg_packer
    cmake --build build32 --config Release --target install

test_script:
- cmd: |
    "%ZPG_ROOT%\bin\zpg_packer.exe" test.zpg -C -A tools\test.jpg
    "%ZPG_ROOT%\bin\zpg_packer.exe" test.zpg -L
    "%ZPG_ROOT%\bin\zpg_packer.exe" test.zpg -E test.jpg
