image: Visual Studio 2015

matrix:
  allow_failures:
    - platform: x86
      configuration: Debug
      ZLIB_ROOT: C:\Program Files (x86)\zlib
      ZPG_ROOT: C:\Program Files (x86)\libZpg
      BUILD_TARGET: Win64
    - platform: x86
      configuration: Release
      ZLIB_ROOT: C:\Program Files (x86)\zlib
      ZPG_ROOT: C:\Program Files (x86)\libZpg
      BUILD_TARGET: Win64
    - platform: x64
      configuration: Debug
      ZLIB_ROOT: C:\Program Files\zlib
      ZPG_ROOT: C:\Program Files\libZpg
    - platform: x64
      configuration: Release
      ZLIB_ROOT: C:\Program Files\zlib
      ZPG_ROOT: C:\Program Files\libZpg

cache:
  #- C:\Program Files (x86)\zlib
  
install:
  - cd c:\projects
  # Download ZLib Source
  - IF NOT EXIST "%ZLIB_ROOT%" (
    curl -LfsS -o zlib-1.2.11.tar.gz http://zlib.net/zlib-1.2.11.tar.gz &&
    7z x zlib-1.2.11.tar.gz &&
    7z x zlib-1.2.11.tar &&
    cd zlib-1.2.11 &&
    md build & cd build &&
    cmake -Werror=dev -G"Visual Studio 14 2015 %BUILD_TARGET%" .. &&
    cd .. &&
    cmake --build build --config Release --target install &&
    cd ..)
  - cd c:\projects\zpg

before_build:
- cmd: |
    md build & cd build
    cmake -Werror=dev -G "Visual Studio 14 2015 Win64" -DCMAKE_BUILD_TYPE=%CONFIGURATION% ..
    cd ..
    
build_script:
- cmd: |
    cmake --build build --config %CONFIGURATION% --target Zpg
    cmake --build build --config %CONFIGURATION% --target zpg_packer
    cmake --build build --config %CONFIGURATION% --target install
    cmake --build build --config %CONFIGURATION% --target package

test_script:
- cmd: |
    "%ZPG_ROOT%\bin\zpg_packer.exe" test.zpg -C -A tools/
    "%ZPG_ROOT%\bin\zpg_packer.exe" test.zpg -L
    "%ZPG_ROOT%\bin\zpg_packer.exe" test.zpg -E tools/test.jpg
    
artifacts:
  - path: build/*.zip
    name: libZpg